### ISSUE TITLE
Writing ntag424 dna

### ISSUE THREAD

**Issue by tedescolor** [icedevml/nfc-ev2-crypto#11]
Good Morning, 
This is almost the only repo dealing with ntag424. I wonder If you have any suggestion how to write these NFC through usb nfc readers. At the moment the only solution I found is through TagXplorer by it allows only one by one modification and not serial writing.  I currently have 2 different usb writers: ACS ACR122U NFC  and uTrust 3700 F. 

Really thanks for the attention

Best regards

**Comment by icedevml** [comment]
Hello,

you can connect to these USB writers through PC/SC standard and then you can just send APDUs to the tag and receive responses. You would have to write an application that executes the appropriate commands, according to the datasheet and application notes provided.

Best regards,
Michał Leszczyński
